name: 同步blackmatrix7
# File: .github/workflows/blackmatrix7-sync.yml

on:
  schedule:
  - cron:  "1 */3 * * *"
  workflow_dispatch:

jobs:
  ziye-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: blackmatrix7-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://${access_token}@github.com/blackmatrix7/ios_rule_script.git"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
